### ISSUE TITLE
update to ring 1.7+ to add namespaced keyword support

### ISSUE THREAD

**Issue by gzmask** [bract/bract.ring#8]
ring 1.6.3's keyword parsing is a bit outdated.

Ring 1.7+ will fix this. See this commit:
https://github.com/ring-clojure/ring/commit/d85a6334f49231ba799c88c5f6bd21b72cfb52a4

**Comment by kumarshantanu** [comment]
Hi @gzmask, _bract.ring_ doesn't pull in the Ring dependency - it only adheres to the Ring contract: https://github.com/ring-clojure/ring/wiki/Concepts So it should work with any Ring version a project uses.

**Comment by gzmask** [comment]
I see, thanks for explaining!
